# TravisCI configuration based on https://github.com/japaric/rust-everywhere
#
# We don't need binary build, only continuous integration, so we don't use
# the deploy step. We also only build a somewhat representative selection of
# targets.

# See: https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
# sudo: false

language: rust
cache: cargo

matrix:
  include:
    # Stable channel
    # Native first
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    # TODO: i686-unknown-linux-musl
    # XXX: musl won't work in current state, because it does not have
    # locale data.
    # Cross-compiles
    - os: linux
      rust: stable
      env: TARGET=armv7-unknown-linux-gnueabihf
      dist: trusty
      addons:
        apt:
          sources:
            - debian-sid
          packages: &armv7_unknown_linux_gnueabihf
            # Cross compiler and cross compiled C libraries
            - gcc-arm-linux-gnueabihf
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
            # Emulator
            - qemu-user
    - os: linux
      rust: stable
      env: TARGET=aarch64-unknown-linux-gnu
      dist: trusty
      addons:
        apt:
          sources:
            - debian-sid
          packages: &aarch64_unknown_linux_gnu
            - gcc-aarch64-linux-gnu
            - libc6-arm64-cross
            - libc6-dev-arm64-cross
            # Emulator
            - qemu-user
    # Beta channel skipped — I don't see much point
    # Nightly channel
    # Native first
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
    # TODO: i686-unknown-linux-musl
    # XXX: musl won't work in current state, because it does not have
    # locale data.
    # Cross-compiles
    - os: linux
      rust: nightly
      env: TARGET=armv7-unknown-linux-gnueabihf
      dist: trusty
      addons:
        apt:
          sources:
            - debian-sid
          packages: *armv7_unknown_linux_gnueabihf
    - os: linux
      rust: stable
      env: TARGET=aarch64-unknown-linux-gnu
      dist: trusty
      addons:
        apt:
          sources:
            - debian-sid
          packages: *aarch64_unknown_linux_gnu

before_install:
    - export PATH="$PATH:$HOME/.cargo/bin"

install:
    - bash ci/install.sh

script:
    - bash ci/script.sh

# vim: set sw=2 sts=2:
